### ISSUE TITLE
Make compatibility_level configurable

### ISSUE THREAD

**Issue by someone1** [Turgon37/docker-smtp-relay#1]
I'd like to modify the default compatibility_level of 0 to 2 for additional features - is this possible to do?

**Comment by Turgon37** [comment]
I thinks yes, I will study to allow modification of any parameter by using environment variable

**Comment by Turgon37** [comment]
Hello, I've just finished to improve this repository, I've added a new build process.
I've also added a new environnement variable RELAY_EXTRAS_SETTINGS that could help you to do what you want :)

Please see an example in the readme.

Feel free to give me any feedback or to send any questions if you need help.
