### ISSUE TITLE
Add multiple SASL users fails due to missing /opt/postfix/saslpasswd2.sh 

### ISSUE THREAD

**Issue by mattstrain** [Turgon37/docker-smtp-relay#17]
Trying to to use this feature doesn't work for me and it seems as though that script used by line 123 of entrypoint.sh does not exist anymore and is simply called  /opt/postfix/saslpasswd.sh ??

```
# ls /opt/postfix
listpasswd.sh  saslpasswd.sh
```

Otherwise its a great image!!

**Comment by Turgon37** [comment]
Hello @mattstrain  thank for reporting this, I'm appologize to having let this image unupdated for too long.

I've prepared a image version 3.2.0 will some improvement and updates in this PR https://github.com/Turgon37/docker-smtp-relay/pull/15. I've published a fix for your issue and than added some tests to prevent this to occur again.

The develop version of this release is available on turgon37/smtp-relay:develop-3.4.9-r0-3.2.0
I've deployed this develop version in my infrastructure to test changes during some days and then I all is fine, I will merge the PR to produce the final production release.

Feel free to test the develop version if you have any time :)
