### ISSUE TITLE
How to run shell script in container?

### ISSUE THREAD

**Issue by rentasad** [Turgon37/docker-smtp-relay#2]
Hi, 

I try to use ure docker smtp-relay and wan't to use your shell scripts.

But I don't know how I can connect me into the container. 
Normally  connect me with the container bash "docker exec -it [containerName] /bin/bash

Can you help how I can use your saslpasswd.sh ?

Best regards

Matthias

**Comment by rentasad** [comment]
Hi, 

now I get it  -  can run it with use with 
`docker exec -it mailRelay /listpasswd.sh`

best regards ;-)

Matthias

**Comment by Turgon37** [comment]
It's a pleasure to not doing anything :)
So, If you have any other questions feel free to send they to me
