### ISSUE TITLE
use docker-smtp-relay to enable scanner to send mail

### ISSUE THREAD

**Issue by pdwonline** [Turgon37/docker-smtp-relay#9]
Hopefully, you can help me getting the smtp-relay configured right. I have a HP Color LaserJet CM6040 MFP that is able to scan documents and send them to an smtp gateway. Since this machine is somewhat older it does not support TLS. I like to solve this using docker-smtp-relay to configure a plain (unsafe) smtp relay in my local network from my printer to docker-smtp-relay an then have that  foreward it using my google account with TLS. Somehow, I could not get this working. This is what I have set up:

My Printer: (IP address 192.168.8.4)  points to smtp gateway 192.168.8.3 on port 25 with no SSL and no authentication.

My server running on 192.168.8.3 in the local network runs docker-smtp-relay using this command:

`docker run --name smtp -d --restart=always -p 25:25 --env-file /opt/smtp/smtp.env turgon37/smtp-relay
`

the /opt/smtp/smtp.env file looks like this:

```
RELAY_HOST=smtp.gmail.com:587
RELAY_LOGIN=myaccount@gmail.com
RELAY_PASSWORD=myGmailPassword
RELAY_USE_TLS=true
RELAY_MYNETWORKS=192.168.8.4
RELAY_MODE=ALLOW_AUTH_NODOMAIN

```
At google I have set the option to accept less secure mail
Since it does'nt work from the printer, I used ssmtp to test from the command line. When I put this in the ssmtp.conf, I can smtp directly to Google, verifying that I could actually mail.

```
FromLineOverride=YES
UseTLS=YES
root=myaccount@gmail.com
mailhub=smtp.gmail.com:587
rewriteDomain=gmail.com
AuthUser=myaccount@gmail.com
AuthPass=myGmailPassword
```

Next, I configure to smtp to docker-smtp-relay using these settings (and that fails):

```
FromLineOverride=YES
UseTLS=NO
root=myaccount@gmail.com
mailhub=182.168.3:25
rewriteDomain=gmail.com

```
What am I doing wrong?

**Comment by Turgon37** [comment]
Hello, have you tried to print postfix logs using the command "docker logs -f <container_name>" to show what is doing during error ?

I recognise that I've not fully tested the outgoing authentication, so maybe something is wrong on container side

**Comment by pdwonline** [comment]
Thanx for your reaction. I have searched the docker logs, but could not find a clue. Should it be possible anyway?

**Comment by Freekers** [comment]
I think you have the wrong IP address in your settings. You have:
```
mailhub=182.168.3:25
```
But, if I understood correctly, this should be
```
mailhub=192.168.8.3:25
```

**Comment by Turgon37** [comment]
@pdwonline  Hello, is your issue still occur ?

I noticed that you dont use the correct syntax to set the gmail smtp address. Use 
[smtp.gmail.com]:587 to prevent MX resolution (but in fact smtp.gmail.com is a valid CNAME so this will not change the result)

**Comment by Turgon37** [comment]
I'm closing this. Feel free to reopen if needed.
